figure(1);
MIN=0.2;
rand_slice = round(rand*size(orig,1));
or_sl = squeeze(real(orig(rand_slice,:,:)));
or_min = min(or_sl(or_sl>MIN));
or_max = max(or_sl(:));
os_sl = squeeze(real(os_pred(rand_slice,:,:)));
os_min = min(os_sl(os_sl>MIN));
os_max = max(os_sl(:));
ts_sl = squeeze(real(ts_pred(rand_slice,:,:)));
ts_min = min(ts_sl(ts_sl>MIN));
ts_max = max(ts_sl(:));

subplot(2, 3, 1);
    imshow(or_sl, [or_min or_max]);
    title('Original');
subplot(2, 3, 2);
    imshow(os_sl, [os_min os_max]);
    title('4 layers');
subplot(2, 3, 3);
    imshow(ts_sl, [ts_min ts_max]);
    title('8 layers');
subplot(2, 3, 4);
    imshow(or_sl - os_sl, []);
    title('4 layers resid');
subplot(2, 3, 5);
    imshow(or_sl - ts_sl, []);
    title('8 layers resid');
subplot(2, 3, 6);
    imshow(os_sl - ts_sl, []);
    title('4/8 resid');